mono:
  replicaCount: 1
  healthcheckPath: /_health
  image:
    repository: outlinewiki/outline
    tag: latest
  port: 3000
  envVars:
    DATABASE_URL: postgres://postgres:godmerch@localhost:5432/godmerch
    PORT: 3000
    REDIS_URL: redis://localhost:6379
  ingress:
    enabled: true
    url: outline.godmerch.com
  postgresql:
    enabled: true
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: 400m
        memory: 750Mi
  redis:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi